### PR TITLE
Design doc Update

### PR DESCRIPTION
**Pull request by hh**

### CODE REVIEW

**Comment by zilman** [comment]
Pending editing passes

**Comment by jbeda** [comment]
Added some questions to the original google doc.  Ping me on slack if you want me to move the here.

**Comment by taylor** [comment]
We have split up the documentation into different areas, including:
- Getting started (new section in README)
  - TL;DR for how to use cross-cloud  => https://github.com/cncf/cross-cloud/issues/53
  - How to use cross-cloud? => https://github.com/cncf/cross-cloud/issues/54
  - How to add your project to cross-cloud? => https://github.com/cncf/cross-cloud/issues/55
- FAQ => https://github.com/cncf/cross-cloud/issues/51
- Roadmap => https://github.com/cncf/cross-cloud/issues/56
- Technical Architecture Design => https://github.com/cncf/cross-cloud/issues/57

This includes feedback from @jbeda and other folks.

**Comment by dlx** [comment]
We have updated the Readme on a new branch.
Closeing PR, will leave this branch up.

**Pull request closed without merging**
